<?php

namespace DatabaseJson\Test\Classes\Helpers;

use DatabaseJson\Core\Helpers\File;
use DatabaseJson\Test\VfsHelper\Config as TestHelper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-03 at 12:57:13.
 */
class FileTest extends \PHPUnit\Framework\TestCase
{

    use TestHelper;

    /**
     * @var File
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->setUpFilesystem();
        $this->object = new File;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::table
     */
    public function testTable()
    {
        $object = $this->object->table('users');
        $this->assertInstanceOf('DatabaseJson\Core\Helpers\File', $object);
        return $object;
    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::getPath
     * @expectedException \DatabaseJson\Core\Helpers\Exception
     * @expectedExceptionMessageRegExp #Please specify the type of file in class: [a-zA-Z0-9]+#
     * @depends testTable
     */
    public function testGetPathIfTypeIsNull($object)
    {
        $object->getPath();
    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::getPath
     * @depends testTable
     */
    public function testGetPath($object)
    {
        $pathStorage = config('databasejson.path', storage_path('app/database-json'));
        $object->setType('data');
        $this->assertSame($pathStorage . 'users.data.json', $object->getPath());
        return $object;
    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::get
     * @depends testTable
     */
    public function testGetDataReturnArray($object)
    {
        $object->setType('data');
        $this->assertInternalType('array', $object->get());
    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::get
     * @depends testTable
     */
    public function testGetConfigReturnObject($object)
    {
        $object->setType('config');
        $this->assertInternalType('object', $object->get());
    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::get
     * @depends testTable
     */
    public function testGetConfigReturnArray($object)
    {
        $object->setType('config');
        $this->assertInternalType('array', $object->get(true));
    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::put
     * @depends testGetPath
     */
    public function testSaveToFile($object)
    {
        $this->assertInternalType('integer', $object->put('test'));
    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::put
     */
    public function testCreateFile()
    {
        $object = $this->object->table('foo');
        $object->setType('bar');
        $this->assertFalse($this->root->hasChild('foo.bar.json'));
        $this->assertInternalType('integer', $object->put('test'));
        $this->assertTrue($this->root->hasChild('foo.bar.json'));
    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::exists
     * @depends testGetPath
     */
    public function testExists($object)
    {
        $this->assertTrue($object->exists());
    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::remove
     */
    public function testRemove()
    {
        $object = $this->object->table('users');
        $object->setType('data');
        $this->assertTrue($this->root->hasChild('users.data.json'));
        $this->assertTrue($object->remove());
        $this->assertFalse($this->root->hasChild('users.data.json'));
    }

    /**
     * @covers \DatabaseJson\Core\Helpers\File::remove
     * @expectedException \DatabaseJson\Core\Helpers\Exception
     * @expectedExceptionMessage Data: File does not exists
     */
    public function testRemoveFileNotExists()
    {
        $object = $this->object->table('ghost');
        $object->setType('data');
        $this->assertFalse($this->root->hasChild('ghost.data.json'));
        $object->remove();
    }

}
